config/routes.rb
Rails.application.routes.draw do
	get	'/products', to: 'products#index'
	get '/products/new', to: 'products#new', as: 'new_product'
	post '/products', to: 'products#create'
	get '/products/:id', to: 'products#show', as: 'product'
	get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
	patch '/products/:id', to: 'products#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(products_params)
		if @product.save
			redirect_to products_path, notice: 'El Producto fue publicado con exito'
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(products_params)
			redirect_to products_path
		else
			render :edit
		end
	end

	private
		def products_params
			params.require(:product).permit(:name, :url, :description)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def form_title
		@product.new_record? ? "Publicar Producto" : "Modificar Producto"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice]%>
	<div class="alert alert-info">
		<%= flash[:notice] %>
	</div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h2><%= form_title %></h2>
			<%= form_for @product do |f| %>
				<div class="form-group">
				<%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Ingresa el nombre del producto'%>
				</div>
				<div class="form-group">
				<%= f.url_field :url, class: 'form-control input-lg', placeholder: 'Ingresa la url del producto'%>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class:'form-control input-lg', placeholder: 'Ingresa la descripcion del producto'%>
				</div>
				<div>
					<%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1>Productos</h1>
			<div class="text-right">
				<%= link_to "Publicar Producto", new_product_path , class: 'btn btn-primary' %>	
			</div>

			<table class="table">
				<tr>
					<th>Id</th>
					<th>Nombre</th>
					<th>URL</th>
					<th>Descripción</th>
					<th></th>
				</tr>
				<% @products.each do |product| %>
					<tr>
						<td><%= product.id %></td>
						<td><%= link_to product.name, product %></td>
						<td><%= product.url %></td>
						<td><%= product.description %></td>
						<td><%= link_to "Editar", edit_product_path(product)%></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/products/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h2>Publicar Producto</h2>
			<%= form_for @product do |f| %>
				<div class="form-group">
				<%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Ingresa el nombre del producto'%>
				</div>
				<div class="form-group">
				<%= f.url_field :url, class: 'form-control input-lg', placeholder: 'Ingresa la url del producto'%>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class:'form-control input-lg', placeholder: 'Ingresa la descripcion del producto'%>
				</div>
				<div>
					<%= f.submit "Publicar Producto", class: "btn btn-primary btn-lg btn-block" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1><%= @product.name %></h1>
			<p><%= @product.description %></p>
			<a href="<%= @product.url %>">Ir al Sitio</a>
		</div>
	</div>
</div>